### ISSUE TITLE
Configuration 

### ISSUE THREAD

**Issue by jamnikr** [anvo/rf24-bcm-java#1]
Hi, 
How to change c++ configuration (RF24 radio(RPI_V2_GPIO_P1_22, RPI_V2_GPIO_P1_24, BCM2835_SPI_SPEED_1MHZ);) to java code?
 thx

**Comment by jamnikr** [comment]
solution:
  RF24 radio = new RF24((short) 25/\*  RPI_V2_GPIO_P1_22_/,
            (short) 8/_ RPI_V2_GPIO_P1_24 _/, (long) 256/_ BCM2835_SPI_SPEED_1MHZ */);

**Comment by anvo** [comment]
See also the example in [GettingStarted.java](https://github.com/anvo/rf24-bcm-java/blob/master/examples/GettingStarted.java)
